from typing import Any
from django.db import models
from authentication.models import User

class Truck(models.Model):
    truck_id = models.AutoField(primary_key=True)
    truck_name = models.CharField(max_length=200)
    truck_plate_number = models.CharField(max_length=10)
    truck_driver = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __init__(self, *args: Any, **kwargs: Any) -> str:
        return f'Truck ID: {self.truck_id}, Truck Name: {self.truck_name}, Driver: {self.truck_driver}'
    
    class Meta:
        verbose_name = 'Truck'
        db_table = 'truck'

class Booking(models.Model):

    STATUS = [
        ('Delivered','Delivered'),
        ('In Transit','In Transit'),
        ('Cancelled','Cancelled'),
    ]

    booking_id = models.AutoField(primary_key=True)
    booking_client_id = models.ForeignKey(User, on_delete=models.CASCADE)
    truck_id = models.ForeignKey(Truck, on_delete=models.CASCADE)
    reservation_date = models.DateField()
    product_type = models.CharField(max_length=200)
    load_count = models.IntegerField()
    reservation_status = models.CharField(max_length=20,choices=STATUS)
    destination_longitude = models.DecimalField(max_digits=10, decimal_places=6)
    destination_latitude = models.DecimalField(max_digits=10, decimal_places=6)


    def __init__(self, *args: Any, **kwargs: Any) -> str:
        return f'Booking ID: {self.booking_id}, Client ID: {self.booking_client_id}, Truck ID: {self.truck_id}'
    
    class Meta:
        verbose_name = 'Booking'
        db_table = 'bookings'


class Report(models.Model):
    report_id = models.AutoField(primary_key=True)
    generate_date = models.DateTimeField(auto_now_add=True)
    generated_by = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'Report'
        db_table = 'reports'

    def __init__(self, *args: Any, **kwargs: Any) -> str:
        return f'Report ID: {self.report_id}, Generated By: {self.generated_by}'